version: "3.9"
services:
  app:
    build: .
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolioservice
